React Pair programming task- header organism
shravyareddy7/zemoso-pairprogramming pull request #1
Opened 2024-06-21 06:02 UTC by shravyareddy7

![Screenshot 2024-06-21 061032](https://github.com/shravyareddy7/zemoso-pairprogramming/assets/167501904/444dee80-ac7d-4521-b97b-f75de8135ee9)

2024-06-24 11:33 UTC, SaiSree-0517 requested changes
assets folder should be in public

2024-06-24 11:33 UTC, SaiSree-0517 commented on src/components/molecules/IconAndText/index.tsx
> +      <TextComponent variant='h1'>GREEN COMMUTE</TextComponent>
dont hard code values get them from constants file

2024-06-24 11:33 UTC, SaiSree-0517 commented on src/components/molecules/Location/index.tsx
> +        <TextComponent variant='body1'>East Maredpally, Secunderabad</TextComponent>
dont hard code values get them from constants file

2024-06-24 13:46 UTC, shravyareddy7 commented on src/components/molecules/IconAndText/index.tsx
> +      <TextComponent variant='h1'>GREEN COMMUTE</TextComponent>
yes, i have made the changes by including constants file

2024-06-24 13:46 UTC, shravyareddy7 commented on src/components/molecules/Location/index.tsx
> +        <TextComponent variant='body1'>East Maredpally, Secunderabad</TextComponent>
yes, i have made the changes by including constants file

2024-06-24 17:59 UTC, SaiSree-0517 commented on src/components/molecules/LogoAndName/index.tsx
instead of passing the values here can create props such that icon+typography can be reused as a molecule

2024-06-25 03:59 UTC, shravyareddy7 commented on src/components/molecules/LogoAndName/index.tsx
oh yes, made changes in the IconAndText component such that it receives props

2024-06-25 04:16 UTC, SaiSree-0517 approved these changes
give meaningfull names for interfaces also

2024-06-25 04:20 UTC, merged